<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

  <!-- Polices de caractère -->
  <link href="https://fonts.googleapis.com/css?family=Poppins|Rubik" rel="stylesheet" />

  <!-- Fichiers css-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" />
  <link rel="stylesheet" href="<?php echo $wwwUrl ?>/css/normalize-8.0.1.css" />
  <link rel="stylesheet" href="<?php echo $wwwUrl ?>/css/style.css" />

  <!-- Fichiers JavaScript-->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="<?php echo $wwwUrl ?>/js/utilities.js"></script>
  <script src="<?php echo $wwwUrl ?>/js/events.js"></script>

  <!--Logo et intitulé du site-->
  <link rel="icon" href="<?php echo $wwwUrl ?>/img/icon.png" sizes="8x8" type="image/png" />
  <title>Restaurant</title>
</head>

<body>
  <header>
    <nav>
      <div class="logo">
        <a href="<?php echo $requestUrl ?>" title="Logo"> <img src="<?php echo $wwwUrl ?>/img/logo.png" alt="Logo" /> </a>
      </div>
      <ul class="nav-links">
        <li><a href="<?php echo $requestUrl ?>" title="Home">Home</a></li>
        <li><a href="<?php echo $requestUrl ?>/menu" title="Menu">Menu</a></li>
        <li><a href="<?php echo $requestUrl ?>/staff" title="Staff">Staff</a></li>
        <li><a href="<?php echo $requestUrl ?>/about" title="About us">About</a></li>

        <!-- Si l'utilisateur n'est pas connecté -->
        <?php if ($userSession->isAuthenticated() == false) : ?>
          <div class="connection">
            <li><a href="<?php echo $requestUrl ?>/user/login" title="Sign in">Sign in</a></li>
            <li><a href="<?php echo $requestUrl ?>/user" title="Register">Register</a></li>
          </div>
          <!-- Si administrateur connecté -->
        <?php elseif ($userSession->getAdmin() == 1) : ?>
          <li><a href="<?php echo $requestUrl ?>/admin/menu" title="Manage menu">Manage menu</a></li>
          <li><a href="<?php echo $requestUrl ?>/admin/staff" title="Manage staff">Manage staff</a></li>
          <div class="connection">
            <li><a href=" <?php echo $requestUrl ?>/user/logout" title="Sign out">Sign out</a></li>
          </div>
          <!-- Si utilisateur normal connecté -->
        <?php else : ?>
          <li><a href="<?php echo $requestUrl ?>/booking" title="Reservation">Reservation</a></li>
          <div class="connection">
            <li><a href=" <?php echo $requestUrl ?>/user/logout" title="Sign out">Sign out</a></li>
          </div>
        <?php endif; ?>
      </ul>
      <!-- Interrupteur de navigation apparaissant en affichage mobile -->
      <div class="burger">
        <div class="burger-line-1"></div>
        <div class="burger-line-2"></div>
        <div class="burger-line-3"></div>
      </div>
    </nav>
  </header>
  <main>
    <?php if ($userSession->isAuthenticated() == true) : ?>
      <p class="welcome">You are logged in as <strong><?php echo $userSession->getFullName() ?></strong></p>
    <?php endif; ?>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>

    <!--Lightbox-->
    <!-- A noter que le paramètre onclick est une manière plus rapide de lier les DOM à leurs fonctions.
        Une autre manière moins pratique aurait été d'ajouter une id, de la réferencer sur JS, puis de lui ajouter un addEventListener click
        pour enfin la lier aux fonctions nextItem et prevItem -->
    <div class="lightbox">
      <div class="lightbox-content">
        <i class="fa fa-times lightbox-close"></i>
        <img src="" alt="current image" class="lightbox-img" onclick="nextItem()" />
        <div class="lightbox-caption">
          <div class="caption-text"></div>
          <div class="caption-counter"></div>
        </div>
        <div class="lightbox-controls">
          <div class="prev-item" onclick="prevItem()"><i class="fa fa-angle-left"></i></div>
          <div class="next-item" onclick="nextItem()"><i class="fa fa-angle-right"></i></div>
        </div>
      </div>
    </div>

  </main>

  <footer>
    <div class="footer-info">
      <ul class="footer-hours">
        <li>
          <h3>Opening hours</h3>
        </li>
        <li>Mon-Fri: 10:30 - 15:00</li>
        <li>Sat: 12:30 - 17:30</li>
        <li>Closed on Sunday</li>
      </ul>
      <ul class="footer-address">
        <li>
          <h3>Address</h3>
        </li>
        <li>50 Avenue Gustave Lafripouille</li>
        <li>78000 — Versailles, France </li>
      </ul>
      <ul class="footer-contact">
        <li>
          <h3>Contact</h3>
        </li>
        <li><a href="tel:123-456-7890" title="Phone"><i class="fa fa-phone"></i> 123 456 7890 </a> </li>
        <li><a href="mailto:contact@restaurant.se" title="E-mail"><i class="fa fa-envelope"></i> contact@restaurant.se </a> </li>
        <div class="social-media">
          <li><a href="" title="Facebook"><i class="fab fa-facebook-f"></i></a></li>
          <li><a href="" title="Twitter"><i class="fab fa-twitter"></i></a></li>
          <li><a href="" title="Google"><i class="fab fa-google-plus-g"></i></a></li>
        </div>
      </ul>

    </div>
    <div class="copyright">
      <p>&copy 2020 Copyright Y H R — <span>for 3WA</span> </p>
    </div>
  </footer>
  <script src="<?php echo $wwwUrl ?>/js/main.js"></script>
</body>

</html>